server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: drive
          uri: http://localhost:8082
          predicates:
            - Path=/undefined/**, 
        - id: indexing
          uri: http://localhost:0
          predicates:
            - Path=/indices/**, 
        - id: streaming
          uri: http://localhost:0
          predicates:
            - Path=/undefined/**, 
        - id: notification
          uri: http://localhost:0
          predicates:
            - Path=/notifies/**, /undefined/**, 
        - id: dashboard
          uri: http://localhost:0
          predicates:
            - Path=, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: drive
          uri: http://drive:8080
          predicates:
            - Path=/undefined/**, 
        - id: indexing
          uri: http://indexing:8080
          predicates:
            - Path=/indices/**, 
        - id: streaming
          uri: http://streaming:8080
          predicates:
            - Path=/undefined/**, 
        - id: notification
          uri: http://notification:8080
          predicates:
            - Path=/notifies/**, /undefined/**, 
        - id: dashboard
          uri: http://dashboard:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
